test-all-TEST: $(TESTS-y)

GEN_UNITS-TEST := $(strip $(foreach test,$(TESTS-y),$(UNITS-$(test)-y)))
GEN_FILES-TEST := $(strip $(TESTS-y) $(GEN_UNITS-TEST))
ALL_TARGETS += $(GEN_FILES-TEST)

$(foreach test,$(TESTS-y),$(foreach unit,$(UNITS-$(test)-y),$(eval UNIT_TEST-$(unit) := $(test))))

clean-all-TEST:
	$(V_ECHO_CMD)$(if $(GEN_FILES-TEST),echo " RM              $(GEN_FILES-TEST)")
	$(V_SILENT_CMD)$(if $(GEN_FILES-TEST),rm -f $(GEN_FILES-TEST))

$(filter %.ok,$(TESTS-y)): $$(DEPS-$$@-y) $$(UNITS-$$@-y)
	$(V_ECHO_CMD)echo " TEST COMPLETE   $@"
	$(V_SILENT_CMD)touch $@

$(filter %.ok,$(GEN_UNITS-TEST)): %.ok: % $$(DEPS-$$@-y) $$(DEPS-$$(UNIT_TEST-$$@)-y)
	$(V_ECHO_CMD)echo " UNIT            $@"
	$(V_SILENT_CMD)$(CMD-$(UNIT_TEST-$@)-y) $<
	$(V_SILENT_CMD)touch $@

$(filter %.notok,$(GEN_UNITS-TEST)): %.notok: % $$(DEPS-$$@-y) $$(DEPS-$$(UNIT_TEST-$$@)-y)
	$(V_ECHO_CMD)echo " UNIT            $@"
	$(V_SILENT_CMD)! $(CMD-$(UNIT_TEST-$@)-y) $<
	$(V_SILENT_CMD)touch $@
