build-all-CUST: $(CUSTBINS-y)

GEN_FILES-CUST := $(strip $(CUSTBINS-y))
ALL_TARGETS += $(GEN_FILES-CUST)

clean-all-CUST:
	$(V_ECHO_CMD)$(if $(GEN_FILES-CUST),echo " RM              $(GEN_FILES-CUST)")
	$(V_SILENT_CMD)$(if $(GEN_FILES-CUST),rm -f $(GEN_FILES-CUST))

$(CUSTBINS-y): $$(DEPS-$$@-y)
