#ifndef ISTEAMPARENTALSETTINGS_H
#define ISTEAMPARENTALSETTINGS_H 1

#define STEAMPARENTALSETTINGS_INTERFACE_VERSION_PREFIX "STEAMPARENTALSETTINGS_INTERFACE_VERSION"

struct ISteamParentalSettings
{
	union
	{
		const void *ptr;
		const struct ISteamParentalSettings001Vtbl *v001;
	} vtbl;
};

enum steam_parental_settings_feature
{
	STEAM_PARENTAL_SETTINGS_FEATURE_INVALID = 0u,
	STEAM_PARENTAL_SETTINGS_FEATURE_STORE = 1u,
	STEAM_PARENTAL_SETTINGS_FEATURE_COMMUNITY = 2u,
	STEAM_PARENTAL_SETTINGS_FEATURE_PROFILE = 3u,
	STEAM_PARENTAL_SETTINGS_FEATURE_FRIENDS = 4u,
	STEAM_PARENTAL_SETTINGS_FEATURE_NEWS = 5u,
	STEAM_PARENTAL_SETTINGS_FEATURE_TRADING = 6u,
	STEAM_PARENTAL_SETTINGS_FEATURE_SETTINGS = 7u,
	STEAM_PARENTAL_SETTINGS_FEATURE_CONSOLE = 8u,
	STEAM_PARENTAL_SETTINGS_FEATURE_BROWSER = 9u,
	STEAM_PARENTAL_SETTINGS_FEATURE_PARENTAL_SETUP = 10u,
	STEAM_PARENTAL_SETTINGS_FEATURE_LIBRARY = 11u,
	STEAM_PARENTAL_SETTINGS_FEATURE_TEST = 12u,
};

struct ISteamParentalSettings *SteamParentalSettings_generic(const char *version);
void SteamParentalSettings_set_version(const char *version);
extern struct ISteamParentalSettings *SteamParentalSettings(void);

#endif /* ISTEAMPARENTALSETTINGS_H */
